"""Signed-distance helpers used to fair the limb/body junctions.

A boolean union can never produce a fillet: two surfaces meeting at an angle
always leave a crease.  To get a flowing transition the body and the limbs are
combined with a *smooth minimum* on their signed distance fields and the result
is re-meshed with marching cubes.

Only the extra fillet material is taken from that blend: the blend solid is
eroded by ``EROSION`` before it is unioned with the exact mesh, so everywhere
away from a junction it sits just inside the exact surface and contributes
nothing.  The precise cup wall, rim round-over and egg cavity therefore stay
exactly as generated by the revolve.
"""

from __future__ import annotations

import numpy as np
import trimesh
from scipy import ndimage
from skimage import measure


# ---------------------------------------------------------------------------
# 2D signed distance to a closed polygon (used for solids of revolution)
# ---------------------------------------------------------------------------

def polygon_sdf(points: np.ndarray, poly: np.ndarray) -> np.ndarray:
    """Signed distance of 2D ``points`` to a closed polygon, negative inside."""
    p = np.asarray(points, dtype=float)
    a = poly
    b = np.roll(poly, -1, axis=0)

    pa = p[:, None, :] - a[None, :, :]
    ba = (b - a)[None, :, :]
    h = np.clip((pa * ba).sum(-1) / (ba * ba).sum(-1), 0.0, 1.0)
    d = np.sqrt((((pa - ba * h[..., None]) ** 2).sum(-1))).min(axis=1)

    # winding number sign test
    ay, by = a[None, :, 1], b[None, :, 1]
    ax, bx = a[None, :, 0], b[None, :, 0]
    py, px = p[:, None, 1], p[:, None, 0]
    cond1 = (ay <= py) & (by > py)
    cond2 = (ay > py) & (by <= py)
    cross = (bx - ax) * (py - ay) / np.where(by == ay, 1e-12, by - ay) + ax - px
    wind = np.where(cond1 & (cross > 0), 1, 0) + np.where(cond2 & (cross > 0), -1, 0)
    inside = wind.sum(axis=1) != 0
    return np.where(inside, -d, d)


class RevolveSDF:
    """Signed distance of a solid of revolution, cached on an (r, z) table."""

    def __init__(self, profile: np.ndarray, r_max: float, z_lo: float,
                 z_hi: float, pitch: float = 0.15):
        self.r0, self.z0, self.pitch = 0.0, z_lo, pitch
        nr = int(np.ceil(r_max / pitch)) + 2
        nz = int(np.ceil((z_hi - z_lo) / pitch)) + 2
        rr = self.r0 + np.arange(nr) * pitch
        zz = self.z0 + np.arange(nz) * pitch
        grid = np.stack(np.meshgrid(rr, zz, indexing="ij"), axis=-1).reshape(-1, 2)
        self.table = polygon_sdf(grid, profile).reshape(nr, nz)

    def __call__(self, xyz: np.ndarray) -> np.ndarray:
        r = np.hypot(xyz[..., 0], xyz[..., 1])
        idx = np.stack([(r - self.r0) / self.pitch,
                        (xyz[..., 2] - self.z0) / self.pitch])
        return ndimage.map_coordinates(self.table, idx, order=1, mode="nearest")


# ---------------------------------------------------------------------------
# Round cone (tapered capsule) distance - one splined limb segment
# ---------------------------------------------------------------------------

def round_cone_sdf(p: np.ndarray, a, b, r1: float, r2: float) -> np.ndarray:
    """Exact distance to the convex hull of two spheres (Inigo Quilez)."""
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    ba = b - a
    l2 = float(ba @ ba)
    rr = r1 - r2
    a2 = l2 - rr * rr
    if l2 < 1e-12 or a2 <= 1e-9:
        # one sphere swallows the other - fall back to the bigger sphere
        c, r = (a, r1) if r1 >= r2 else (b, r2)
        return np.linalg.norm(p - c, axis=-1) - r

    il2 = 1.0 / l2
    pa = p - a
    y = pa @ ba
    z = y - l2
    x = pa * l2 - ba * y[..., None]
    x2 = (x * x).sum(-1)
    y2 = y * y * l2
    z2 = z * z * l2
    k = np.sign(rr) * rr * rr * x2

    far = np.sign(z) * a2 * z2 > k
    near = np.sign(y) * a2 * y2 < k
    core = (np.sqrt(np.maximum(x2 * a2 * il2, 0.0)) + y * rr) * il2 - r1
    return np.where(far, np.sqrt(x2 + z2) * il2 - r2,
                    np.where(near, np.sqrt(x2 + y2) * il2 - r1, core))


def smin(a: np.ndarray, b: np.ndarray, k: float) -> np.ndarray:
    """Polynomial smooth minimum - this is what creates the fillet."""
    h = np.clip(0.5 + 0.5 * (b - a) / k, 0.0, 1.0)
    return b * (1.0 - h) + a * h - k * h * (1.0 - h)


# ---------------------------------------------------------------------------
# Blend solid
# ---------------------------------------------------------------------------

def blend_solid(body_sdf: RevolveSDF, cavity_sdf: RevolveSDF, limb_nodes,
                bounds: np.ndarray, blend: float, erosion: float,
                pitch: float, z_floor: float = 0.0) -> trimesh.Trimesh:
    """Marching-cubes mesh of smin(body, limbs) eroded by ``erosion``."""
    lo = bounds[0] - 4.0
    hi = bounds[1] + 4.0
    dims = np.ceil((hi - lo) / pitch).astype(int) + 1
    axes = [lo[i] + np.arange(dims[i]) * pitch for i in range(3)]
    grid = np.stack(np.meshgrid(*axes, indexing="ij"), axis=-1)

    far = float(np.linalg.norm(hi - lo))

    # The capsules of one limb must be combined with a *hard* minimum.  Using
    # the smooth minimum here would inflate every limb by up to blend/4 along
    # its whole length instead of only fairing it into the body.
    limb_field = np.full(dims, far, dtype=float)
    for nodes in limb_nodes:
        for a, b in zip(nodes[:-1], nodes[1:]):
            r = max(a[3], b[3]) + blend + 2.0 * pitch
            box_lo = np.minimum(a[:3], b[:3]) - r
            box_hi = np.maximum(a[:3], b[:3]) + r
            i0 = np.clip(np.floor((box_lo - lo) / pitch).astype(int), 0, dims - 1)
            i1 = np.clip(np.ceil((box_hi - lo) / pitch).astype(int) + 1, 0, dims)
            if np.any(i1 <= i0):
                continue
            sl = tuple(slice(i0[i], i1[i]) for i in range(3))
            d = round_cone_sdf(grid[sl], a[:3], b[:3], a[3], b[3])
            np.minimum(limb_field[sl], d, out=limb_field[sl])

    field = smin(body_sdf(grid), limb_field, blend)

    # erode, then subtract the cavity dilated by the same amount so the blend
    # can never shrink the egg pocket
    field = np.maximum(field + erosion, erosion - cavity_sdf(grid))

    # the fillet bulges outward in every direction, including downwards past the
    # table.  Clip it to the build plate, otherwise dropping the figure to z=0
    # lifts the cup off the bed.
    field = np.maximum(field, z_floor - grid[..., 2])

    # a positive shell guarantees marching cubes closes the surface
    field = np.pad(field, 1, mode="constant", constant_values=far)

    verts, faces, _, _ = measure.marching_cubes(field, level=0.0,
                                                spacing=(pitch,) * 3)
    verts += lo - pitch
    mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
    mesh.merge_vertices()
    mesh.fix_normals()
    return mesh
